-- Total records
SELECT COUNT(*) FROM online_retail_transactions;

--What is the total revenue generated by the business?
SELECT 
    ROUND(SUM("Total_Spend")::numeric, 2) AS total_revenue
FROM online_retail_transactions;

--Which are the top 10 countries by total revenue?
SELECT 
    "Country",
    ROUND(SUM("Total_Spend")::numeric, 2) AS revenue
FROM online_retail_transactions
GROUP BY "Country"
ORDER BY revenue DESC
LIMIT 10;

--Who are the top 10 customers by total spending?
SELECT 
    "Customer ID",
    ROUND(SUM("Total_Spend")::numeric, 2) AS total_spent
FROM online_retail_transactions
GROUP BY "Customer ID"
ORDER BY total_spent DESC
LIMIT 10;

--What is the revenue contribution of each customer segment?
SELECT 
    "Customer_Segment",
    ROUND(SUM("Total_Spend")::numeric, 2) AS revenue
FROM online_retail_transactions
GROUP BY "Customer_Segment"
ORDER BY revenue DESC;

--How many customers belong to each customer segment?
SELECT 
    "Customer_Segment",
    COUNT(DISTINCT "Customer ID") AS customer_count
FROM online_retail_transactions
GROUP BY "Customer_Segment"
ORDER BY customer_count DESC;

--What is the average order value (AOV)?
SELECT 
    ROUND(
        (SUM("Total_Spend") / COUNT(DISTINCT "Invoice"))::numeric,
        2
    ) AS avg_order_value
FROM online_retail_transactions;

--Which are the top 10 products by revenue?
SELECT 
    "Description",
    ROUND(SUM("Total_Spend")::numeric, 2) AS product_revenue
FROM online_retail_transactions
GROUP BY "Description"
ORDER BY product_revenue DESC
LIMIT 10;

--What is the monthly revenue trend?
SELECT 
    "Month",
    ROUND(SUM("Total_Spend")::numeric, 2) AS monthly_revenue
FROM online_retail_transactions
GROUP BY "Month"
ORDER BY "Month";

--How many repeat customers does the business have?
SELECT COUNT(*) AS repeat_customers
FROM (
    SELECT "Customer ID"
    FROM online_retail_transactions
    GROUP BY "Customer ID"
    HAVING COUNT(DISTINCT "Invoice") > 1
) t;


--Which customers placed the highest number of orders?
SELECT 
    "Customer ID",
    COUNT(DISTINCT "Invoice") AS total_orders
FROM online_retail_transactions
GROUP BY "Customer ID"
ORDER BY total_orders DESC
LIMIT 10;




